// frontend/app/taro/src/pages/about/index.tsx
import {useTranslation} from 'react-i18next';
import {View, Text} from '@tarojs/components';
import XIcon from '@/plugins/xicon';
import {usePageTitle} from '@/hooks/usePageTitle';

export default function AboutPage() {
    const {t} = useTranslation();
    usePageTitle('page.title.about');

    const features = [
        {icon: 'carbon:document-add', title: t('page.about.feature_content'), description: t('page.about.feature_content_desc')},
        {icon: 'carbon:cloud-upload', title: t('page.about.feature_multi_tenant'), description: t('page.about.feature_multi_tenant_desc')},
        {icon: 'carbon:security', title: t('page.about.feature_security'), description: t('page.about.feature_security_desc')},
        {icon: 'carbon:api', title: t('page.about.feature_api'), description: t('page.about.feature_api_desc')},
        {icon: 'carbon:collaborate', title: t('page.about.feature_collaboration'), description: t('page.about.feature_collaboration_desc')},
        {icon: 'carbon:analytics', title: t('page.about.feature_analytics'), description: t('page.about.feature_analytics_desc')},
    ];

    const stats = [
        {number: '10K+', label: t('page.about.stat_users'), icon: 'carbon:user-multiple'},
        {number: '500+', label: t('page.about.stat_projects'), icon: 'carbon:folder'},
        {number: '99.9%', label: t('page.about.stat_uptime'), icon: 'carbon:checkmark-outline'},
        {number: '24/7', label: t('page.about.stat_support'), icon: 'carbon:headset'},
    ];

    return (
        <View className='min-h-screen w-full bg-pageBg pb-[240rpx]'>
            {/* 页面标题 */}
            <View className='bg-cardBg px-[24rpx] pt-[40rpx] pb-[24rpx] border-b-[1rpx] border-splitLine'>
                <Text className='text-title font-bold text-textMain block mb-[8rpx]'>{t('page.about.title')}</Text>
                <Text className='text-desc text-textSec block'>{t('page.about.subtitle')}</Text>
            </View>

            {/* 关于我们 */}
            <View className='px-[24rpx] pt-[32rpx]'>
                <View className='rounded-[32rpx] bg-cardBg p-[32rpx]'>
                    <Text className='text-card-title font-bold text-textMain block mb-[16rpx]'>{t('page.about.about_us')}</Text>
                    <Text className='text-body text-textSec leading-[1.8] block mb-[16rpx]'>{t('page.about.about_us_desc_1')}</Text>
                    <Text className='text-body text-textSec leading-[1.8] block mb-[16rpx]'>{t('page.about.about_us_desc_2')}</Text>
                    <Text className='text-body text-textSec leading-[1.8]'>{t('page.about.about_us_desc_3')}</Text>
                </View>
            </View>

            {/* 统计数据 - 2x2 网格 */}
            <View className='px-[24rpx] pt-[32rpx]'>
                <View className='grid grid-cols-2 gap-[24rpx]'>
                    {stats.map((stat) => (
                        <View key={stat.label} className='rounded-[32rpx] bg-cardBg p-[32rpx]'>
                            <View className='flex items-center gap-[12rpx] mb-[12rpx]'>
                                <View className='w-[48rpx] h-[48rpx] rounded-[16rpx] bg-primary/10 flex items-center justify-center'>
                                    <XIcon name={stat.icon} size={18} className='text-primary' />
                                </View>
                                <Text className='text-card-title font-bold text-primary'>{stat.number}</Text>
                            </View>
                            <Text className='text-tips text-textSec'>{stat.label}</Text>
                        </View>
                    ))}
                </View>
            </View>

            {/* 功能特性 */}
            <View className='px-[24rpx] pt-[32rpx]'>
                <View className='rounded-[32rpx] bg-cardBg p-[32rpx]'>
                    <Text className='text-card-title font-bold text-textMain block mb-[8rpx]'>{t('page.about.features')}</Text>
                    <Text className='text-desc text-textSec mb-[32rpx]'>{t('page.about.features_desc')}</Text>
                    <View className='grid grid-cols-2 gap-[24rpx]'>
                        {features.map((feature) => (
                            <View key={feature.title} className='rounded-[24rpx] bg-pageBg p-[24rpx]'>
                                <View className='flex items-center justify-center w-[72rpx] h-[72rpx] rounded-[24rpx] bg-primary/10 mb-[16rpx]'>
                                    <XIcon name={feature.icon} size={28} className='text-primary' />
                                </View>
                                <Text className='text-desc font-bold text-textMain block mb-[8rpx]'>{feature.title}</Text>
                                <Text
                                  className='text-tips text-textSec leading-[1.6]'
                                  style={{
                                    overflow: 'hidden',
                                    textOverflow: 'ellipsis',
                                    display: '-webkit-box',
                                    WebkitLineClamp: 3,
                                    WebkitBoxOrient: 'vertical',
                                  }}
                                >
                                    {feature.description}
                                </Text>
                            </View>
                        ))}
                    </View>
                </View>
            </View>
        </View>
    );
}

// frontend/app/vue/app/pages/about.vue
<script setup lang="ts">
const { t } = useI18n()

useHead({ title: t('page.about.title') })
</script>

<template>
  <div class="w-full">
    <LayoutPageHero
      :title="t('page.about.title')"
      :subtitle="t('page.about.subtitle')"
      :description="t('page.about.description')"
      icon="carbon:information"
      :icon-size="56"
      size="lg"
    />

    <!-- About Section -->
    <section class="w-full bg-background py-20">
      <div class="w-full max-w-[1200px] mx-auto px-8 max-md:px-4">
        <div class="grid grid-cols-1 gap-12 lg:grid-cols-2 lg:gap-16">
          <div class="antialiased">
            <h2 class="mb-6 text-3xl font-bold text-foreground">{{ t('page.about.about_us') }}</h2>
            <p class="mb-4 text-[15px] leading-loose tracking-normal text-muted-foreground">{{ t('page.about.about_us_desc_1') }}</p>
            <p class="mb-4 text-[15px] leading-loose tracking-normal text-muted-foreground">{{ t('page.about.about_us_desc_2') }}</p>
            <p class="text-[15px] leading-loose tracking-normal text-muted-foreground">{{ t('page.about.about_us_desc_3') }}</p>
          </div>
          <div class="grid grid-cols-2 gap-4">
            <div v-for="stat in [
              { num: '10K+', label: t('page.about.stat_users') },
              { num: '500+', label: t('page.about.stat_projects') },
              { num: '99.9%', label: t('page.about.stat_uptime') },
              { num: '24/7', label: t('page.about.stat_support') },
            ]" :key="stat.label" class="rounded-xl border border-border bg-card p-6 text-center shadow-sm">
              <div class="mb-3 text-3xl font-bold text-primary">{{ stat.num }}</div>
              <div class="text-[15px] font-medium text-muted-foreground">{{ stat.label }}</div>
            </div>
          </div>
        </div>
      </div>
    </section>

    <!-- Features -->
    <section class="w-full bg-muted/30 py-20">
      <div class="w-full max-w-[1200px] mx-auto px-8 max-md:px-4">
        <div class="mb-12 text-center">
          <h2 class="mb-4 text-3xl font-bold text-foreground">{{ t('page.about.features') }}</h2>
          <p class="text-muted-foreground">{{ t('page.about.features_desc') }}</p>
        </div>
        <div class="grid grid-cols-[repeat(auto-fit,minmax(280px,1fr))] gap-6">
          <div
            v-for="feature in [
              { icon: 'carbon:document-add', title: t('page.about.feature_content'), description: t('page.about.feature_content_desc') },
              { icon: 'carbon:cloud-upload', title: t('page.about.feature_multi_tenant'), description: t('page.about.feature_multi_tenant_desc') },
              { icon: 'carbon:security', title: t('page.about.feature_security'), description: t('page.about.feature_security_desc') },
              { icon: 'carbon:api', title: t('page.about.feature_api'), description: t('page.about.feature_api_desc') },
              { icon: 'carbon:collaborate', title: t('page.about.feature_collaboration'), description: t('page.about.feature_collaboration_desc') },
              { icon: 'carbon:analytics', title: t('page.about.feature_analytics'), description: t('page.about.feature_analytics_desc') },
            ]"
            :key="feature.title"
            class="group rounded-xl border border-border bg-card p-8 text-center shadow-sm transition-all duration-300 hover:-translate-y-1 hover:border-primary/40 hover:shadow-lg"
          >
            <div class="mx-auto mb-4 flex h-16 w-16 items-center justify-center rounded-xl bg-primary/10 text-primary transition-all duration-300 group-hover:bg-primary group-hover:text-white group-hover:shadow-md">
              <XIcon :icon="feature.icon" :size="32" />
            </div>
            <h3 class="mb-2 text-lg font-bold text-foreground transition-colors group-hover:text-primary">{{ feature.title }}</h3>
            <p class="text-sm leading-relaxed text-muted-foreground">{{ feature.description }}</p>
          </div>
        </div>
      </div>
    </section>

    <!-- Team -->
    <section class="w-full bg-background py-20">
      <div class="w-full max-w-[1200px] mx-auto px-8 max-md:px-4">
        <div class="mb-12 text-center">
          <h2 class="mb-4 text-3xl font-bold text-foreground">{{ t('page.about.team') }}</h2>
          <p class="text-muted-foreground">{{ t('page.about.team_desc') }}</p>
        </div>
        <div class="grid grid-cols-[repeat(auto-fit,minmax(250px,1fr))] gap-6">
          <div
            v-for="member in [
              { name: t('page.about.team_member_1'), role: t('page.about.team_role_1'), avatar: '/logo.png' },
              { name: t('page.about.team_member_2'), role: t('page.about.team_role_2'), avatar: '/logo.png' },
              { name: t('page.about.team_member_3'), role: t('page.about.team_role_3'), avatar: '/logo.png' },
            ]"
            :key="member.name"
            class="rounded-xl border border-border bg-card p-8 text-center shadow-sm transition-all duration-300 hover:-translate-y-1 hover:shadow-lg"
          >
            <div class="mx-auto mb-4 h-[120px] w-[120px] overflow-hidden rounded-full ring-2 ring-primary/20">
              <img :src="member.avatar" :alt="member.name" width="120" height="120" />
            </div>
            <h3 class="mb-2 text-lg font-bold text-foreground">{{ member.name }}</h3>
            <p class="text-xs text-muted-foreground/80">{{ member.role }}</p>
          </div>
        </div>
      </div>
    </section>

    <!-- Values -->
    <section class="w-full bg-muted/30 py-20">
      <div class="w-full max-w-[1200px] mx-auto px-8 max-md:px-4">
        <div class="mb-12 text-center">
          <h2 class="mb-4 text-3xl font-bold text-foreground">{{ t('page.about.values') }}</h2>
          <p class="text-muted-foreground">{{ t('page.about.values_desc') }}</p>
        </div>
        <div class="grid grid-cols-1 gap-6 md:grid-cols-3">
          <div
            v-for="value in [
              { title: t('page.about.value_innovation'), desc: t('page.about.value_innovation_desc') },
              { title: t('page.about.value_reliability'), desc: t('page.about.value_reliability_desc') },
              { title: t('page.about.value_customer'), desc: t('page.about.value_customer_desc') },
            ]"
            :key="value.title"
            class="rounded-xl border border-border bg-card p-8 shadow-sm transition-all duration-300 hover:-translate-y-1 hover:shadow-lg"
          >
            <h3 class="mb-3 text-xl font-bold text-primary">{{ value.title }}</h3>
            <p class="text-sm leading-relaxed text-muted-foreground mt-2">{{ value.desc }}</p>
          </div>
        </div>
      </div>
    </section>

    <!-- CTA -->
    <section class="w-full bg-primary/5 py-20">
      <div class="w-full max-w-[1200px] mx-auto px-8 max-md:px-4">
        <div class="mx-auto max-w-[800px] text-center">
          <h2 class="mb-4 text-3xl font-bold text-foreground">{{ t('page.about.cta_title') }}</h2>
          <p class="mb-8 text-lg text-muted-foreground">{{ t('page.about.cta_desc') }}</p>
          <div class="flex flex-wrap justify-center gap-4">
            <UiButton size="lg" class="rounded-lg px-6 py-2.5 font-medium">{{ t('page.about.cta_explore') }}</UiButton>
            <UiButton variant="outline" size="lg" class="rounded-lg px-6 py-2.5 font-medium">{{ t('page.about.cta_contact') }}</UiButton>
          </div>
        </div>
      </div>
    </section>
  </div>
</template>
