// frontend/app/react/src/app/[locale]/disclaimer/page.tsx
'use client';

import {useTranslations} from 'next-intl';
import LegalPage from '@/components/layout/LegalPage';

export default function DisclaimerPage() {
    const t = useTranslations('page.legal.disclaimer');

    return (
        <LegalPage
            icon="carbon:warning"
            title={t('title')}
            description={t('description')}
            items={[t('item_1'), t('item_2'), t('item_3')]}
        />
    );
}

// frontend/app/vue/app/pages/disclaimer.vue
<script setup lang="ts">
const { t } = useI18n()

useHead({ title: t('page.legal.disclaimer.title') })
</script>

<template>
  <LayoutLegalPage
    icon="carbon:warning"
    :title="t('page.legal.disclaimer.title')"
    :description="t('page.legal.disclaimer.description')"
    :items="[t('page.legal.disclaimer.item_1'), t('page.legal.disclaimer.item_2'), t('page.legal.disclaimer.item_3')]"
  />
</template>
