// frontend/app/react/src/app/[locale]/login/page.tsx
'use client';

import {useState} from 'react';
import {useTranslations} from 'next-intl';
import {useI18nRouter} from "@/i18n/helpers";

import AuthLayout, {type AuthTab} from '@/components/auth/AuthLayout';

import AccountLoginPage from './components/AccountLoginPage';
import EmailLoginPage from './components/EmailLoginPage';
import PhoneLoginPage from './components/PhoneLoginPage';
import OtherLoginPage from './components/OtherLoginPage';

export default function LoginPage() {
    const t = useTranslations('authentication');
    const router = useI18nRouter();
    const [activeTab, setActiveTab] = useState<AuthTab>('account');

    const textBtn = 'text-sm text-primary transition-colors hover:text-primary/80 hover:underline cursor-pointer bg-transparent border-none';

    return (
        <AuthLayout
            title={t('login.title')}
            subtitle={t('login.login_with')}
            activeTab={activeTab}
            onTabChange={setActiveTab}
            switchLink={
                <p>
                    {t('login.no_account')}
                    <button className={`${textBtn} ms-1`} onClick={() => router.push('/register')}>
                        {t('login.register_now')}
                    </button>
                </p>
            }
        >
            {activeTab === 'account' && <AccountLoginPage/>}
            {activeTab === 'email' && <EmailLoginPage/>}
            {activeTab === 'phone' && <PhoneLoginPage/>}
            {activeTab === 'other' && <OtherLoginPage/>}
        </AuthLayout>
    );
}

// frontend/app/vue/app/pages/login.vue
<script setup lang="ts">
definePageMeta({ layout: 'auth' })

const { t } = useI18n()
const localePath = useLocalePath()

useHead({ title: t('authentication.login.title') })

const activeTab = ref<string>('account')

const tabs = computed(() => [
  { key: 'account', label: t('authentication.login.tab_account') },
  { key: 'email', label: t('authentication.login.tab_email') },
  { key: 'phone', label: t('authentication.login.tab_phone') },
  { key: 'other', label: t('authentication.login.tab_other') },
])

const textBtn = 'cursor-pointer border-none bg-transparent text-sm text-primary transition-colors hover:text-primary/80 hover:underline'
</script>

<template>
  <AuthLayout
    :title="t('authentication.login.title')"
    :subtitle="t('authentication.login.login_with')"
    :active-tab="activeTab"
    :tabs="tabs"
    @update:active-tab="activeTab = $event"
  >
    <AuthAccountLogin v-if="activeTab === 'account'" />
    <AuthEmailLogin v-else-if="activeTab === 'email'" />
    <AuthPhoneLogin v-else-if="activeTab === 'phone'" />
    <AuthOtherLogin v-else-if="activeTab === 'other'" />

    <template #switchLink>
      {{ t('authentication.login.no_account') }}
      <button :class="textBtn" class="ms-1" @click="navigateTo(localePath('/register'))">
        {{ t('authentication.login.register_now') }}
      </button>
    </template>
  </AuthLayout>
</template>
