// frontend/app/react/src/app/[locale]/register/page.tsx
'use client';

import {useState} from 'react';
import {useTranslations} from 'next-intl';
import {useI18nRouter} from "@/i18n/helpers";

import AuthLayout, {type AuthTab} from '@/components/auth/AuthLayout';

import AccountRegisterPage from './components/AccountRegisterPage';
import EmailRegisterPage from './components/EmailRegisterPage';
import PhoneRegisterPage from './components/PhoneRegisterPage';
import OtherRegisterPage from './components/OtherRegisterPage';

export default function RegisterPage() {
    const t = useTranslations('authentication');
    const router = useI18nRouter();
    const [activeTab, setActiveTab] = useState<AuthTab>('account');

    const textBtn = 'text-sm text-primary transition-colors hover:text-primary/80 hover:underline cursor-pointer bg-transparent border-none';

    return (
        <AuthLayout
            title={t('register.title')}
            subtitle={t('register.register_with')}
            activeTab={activeTab}
            onTabChange={setActiveTab}
            switchLink={
                <p>
                    {t('register.already_have_account')}
                    <button className={`${textBtn} ms-1`} onClick={() => router.push('/login')}>
                        {t('register.login_now')}
                    </button>
                </p>
            }
        >
            {activeTab === 'account' && <AccountRegisterPage/>}
            {activeTab === 'email' && <EmailRegisterPage/>}
            {activeTab === 'phone' && <PhoneRegisterPage/>}
            {activeTab === 'other' && <OtherRegisterPage/>}
        </AuthLayout>
    );
}

// frontend/app/vue/app/pages/register.vue
<script setup lang="ts">
definePageMeta({ layout: 'auth' })

const { t } = useI18n()
const localePath = useLocalePath()

useHead({ title: t('authentication.register.title') })

const activeTab = ref<string>('account')

const tabs = computed(() => [
  { key: 'account', label: t('authentication.login.tab_account') },
  { key: 'email', label: t('authentication.login.tab_email') },
  { key: 'phone', label: t('authentication.login.tab_phone') },
  { key: 'other', label: t('authentication.login.tab_other') },
])

const textBtn = 'cursor-pointer border-none bg-transparent text-sm text-primary transition-colors hover:text-primary/80 hover:underline'
</script>

<template>
  <AuthLayout
    :title="t('authentication.register.title')"
    :subtitle="t('authentication.register.register_with')"
    :active-tab="activeTab"
    :tabs="tabs"
    @update:active-tab="activeTab = $event"
  >
    <AuthAccountRegister v-if="activeTab === 'account'" />
    <AuthEmailRegister v-else-if="activeTab === 'email'" />
    <AuthPhoneRegister v-else-if="activeTab === 'phone'" />
    <AuthOtherRegister v-else-if="activeTab === 'other'" />

    <template #switchLink>
      {{ t('authentication.register.already_have_account') }}
      <button :class="textBtn" class="ms-1" @click="navigateTo(localePath('/login'))">
        {{ t('authentication.register.login_now') }}
      </button>
    </template>
  </AuthLayout>
</template>
