// frontend/app/react/src/app/[locale]/search/page.tsx
'use client';

import {useState, useEffect} from 'react';
import {useSearchParams} from 'next/navigation';
import {useTranslations} from 'next-intl';
import {Skeleton} from '@/components/ui/skeleton';
import {AppEmpty} from '@/components/ui';
import {SearchX, FileText, ChevronRight} from 'lucide-react';

import {fetchSearchPosts} from '@/api/hooks/post';
import PageHero from '@/components/layout/PageHero';
import SectionContainer from '@/components/layout/SectionContainer';

import {useI18nRouter} from '@/i18n/helpers';

interface SearchHit {
    postId?: number;
    language?: string;
    title?: string;
}

interface SearchResponse {
    items?: SearchHit[];
    total?: number;
}

export default function SearchPage() {
    const t = useTranslations('page');
    const router = useI18nRouter();
    const searchParams = useSearchParams();
    const query = searchParams.get('q')?.trim() ?? '';

    const [loading, setLoading] = useState(false);
    const [hits, setHits] = useState<SearchHit[]>([]);
    const [total, setTotal] = useState(0);

    useEffect(() => {
        if (!query) {
            setHits([]);
            setTotal(0);
            return;
        }
        let cancelled = false;
        setLoading(true);
        fetchSearchPosts({query, pageSize: 20})
            .then((res) => {
                if (cancelled) return;
                const data = res as unknown as SearchResponse;
                setHits(data?.items ?? []);
                setTotal(data?.total ?? 0);
            })
            .catch((err) => {
                console.error('Search failed:', err);
                if (cancelled) return;
                setHits([]);
                setTotal(0);
            })
            .finally(() => {
                if (!cancelled) setLoading(false);
            });
        return () => {
            cancelled = true;
        };
    }, [query]);

    const openPost = (postId?: number) => {
        if (!postId) return;
        router.push(`/post/${postId}`);
        if (typeof window !== 'undefined') {
            window.scrollTo({top: 0, behavior: 'smooth'});
        }
    };

    return (
        <div className="w-full">
            <PageHero
                title={t('posts.search')}
                description={query ? `"${query}"` : undefined}
                icon="lucide:search"
                size="md"
            />

            <SectionContainer>
                {/* 加载中 */}
                {loading ? (
                    <div className="grid gap-3">
                        {[...Array(5)].map((_, i) => (
                            <Skeleton key={i} className="h-16 w-full"/>
                        ))}
                    </div>
                ) : !query ? (
                    <AppEmpty
                        description={t('posts.search_placeholder')}
                        inContainer
                        image={<span className="i-carbon:search text-[64px]"/>}
                    />
                ) : hits.length === 0 ? (
                    <AppEmpty
                        description={t('posts.no_search_results', {query})}
                        inContainer
                        image={<SearchX className="h-16 w-16 text-muted-foreground/40"/>}
                    />
                ) : (
                    <div>
                        <p className="mb-6 text-sm text-muted-foreground">
                            {t('posts.search_results_count', {count: total})}
                        </p>
                        <div className="grid gap-3">
                            {hits.map((hit, idx) => (
                                <article
                                    key={hit.postId ?? idx}
                                    onClick={() => openPost(hit.postId)}
                                    className="group flex cursor-pointer items-center gap-3 rounded-xl border border-border bg-card p-5 shadow-sm transition-all duration-300 hover:-translate-y-0.5 hover:border-primary/40 hover:shadow-md"
                                >
                                    <FileText className="h-5 w-5 shrink-0 text-muted-foreground transition-colors group-hover:text-primary"/>
                                    <h3 className="line-clamp-2 flex-1 text-base font-semibold text-foreground transition-colors group-hover:text-primary">
                                        {hit.title}
                                    </h3>
                                    <ChevronRight className="h-[18px] w-[18px] shrink-0 text-muted-foreground opacity-0 transition-opacity group-hover:opacity-100"/>
                                </article>
                            ))}
                        </div>
                    </div>
                )}
            </SectionContainer>
        </div>
    );
}

// frontend/app/vue/app/pages/search.vue
<script setup lang="ts">
import { fetchSearchPosts } from '@/api/composables/post'

const { t } = useI18n()
const route = useRoute()
const localePath = useLocalePath()

const query = computed(() => (route.query.q as string)?.trim() ?? '')

useHead({ title: () => query.value ? `${t('page.posts.search')}: ${query.value}` : t('page.posts.search') })

// 依赖 query 触发重新搜索
const { data, pending, error } = await useAsyncData(
  () => `search-${query.value}`,
  () => query.value ? fetchSearchPosts({ query: query.value, pageSize: 20 }) : Promise.resolve(null),
  { watch: [query] },
)

const hits = computed(() => data.value?.items ?? [])
const total = computed(() => data.value?.total ?? 0)

function openPost(postId?: number) {
  if (!postId) return
  navigateTo(localePath(`/post/${postId}`))
  window.scrollTo({ top: 0, behavior: 'smooth' })
}
</script>

<template>
  <div class="w-full">
    <LayoutPageHero
      :title="t('page.posts.search')"
      :description='query ? `"${query}"` : ""'
      icon="lucide:search"
      size="md"
    />

    <LayoutSectionContainer>
      <!-- 加载中 -->
      <div v-if="pending" class="flex justify-center py-20">
        <UiSpinner size="lg" class="text-primary" />
      </div>

      <!-- 出错 -->
      <div v-else-if="error" class="py-20 text-center text-muted-foreground">
        {{ t('page.posts.search_failed') }}
      </div>

      <!-- 无关键词 -->
      <div v-else-if="!query" class="py-20 text-center text-muted-foreground">
        {{ t('page.posts.search_placeholder') }}
      </div>

      <!-- 无结果 -->
      <div v-else-if="hits.length === 0" class="flex flex-col items-center py-20 text-muted-foreground">
        <XIcon icon="lucide:search-x" :size="48" class="mb-4 opacity-50" />
        <p>{{ t('page.posts.no_search_results', { query }) }}</p>
      </div>

      <!-- 结果列表 -->
      <div v-else>
        <p class="mb-6 text-sm text-muted-foreground">
          {{ t('page.posts.search_results_count', { count: total }) }}
        </p>
        <div class="grid gap-3">
          <article
            v-for="hit in hits"
            :key="hit.postId"
            class="group flex cursor-pointer items-center gap-3 rounded-xl border border-border bg-card p-5 shadow-sm transition-all duration-300 hover:-translate-y-0.5 hover:border-primary/40 hover:shadow-md"
            @click="openPost(hit.postId)"
          >
            <XIcon icon="carbon:document" :size="20" class="shrink-0 text-muted-foreground transition-colors group-hover:text-primary" />
            <h3 class="line-clamp-2 flex-1 text-base font-semibold text-foreground transition-colors group-hover:text-primary">
              {{ hit.title }}
            </h3>
            <XIcon icon="lucide:chevron-right" :size="18" class="shrink-0 text-muted-foreground opacity-0 transition-opacity group-hover:opacity-100" />
          </article>
        </div>
      </div>
    </LayoutSectionContainer>
  </div>
</template>
