// frontend/app/taro/src/components/layout/BackToTop.tsx
import React, {useEffect, useState} from 'react';
import {View} from '@tarojs/components';
import Taro from '@tarojs/taro';
import XIcon from '@/plugins/xicon';

const BackToTop: React.FC<{
    scrollThreshold?: number;
    onClick?: () => void;
}> = ({scrollThreshold = 500, onClick}) => {
    const [visible, setVisible] = useState(false);

    useEffect(() => {
        if (typeof window === 'undefined') return;
        const handleScroll = () => setVisible(window.scrollY > scrollThreshold);
        window.addEventListener('scroll', handleScroll);
        handleScroll();
        return () => window.removeEventListener('scroll', handleScroll);
    }, [scrollThreshold]);

    if (!visible) return null;

    return (
        <View
          className='fixed bottom-[40rpx] end-[40rpx] z-[999] flex w-[88rpx] h-[88rpx] items-center justify-center rounded-full bg-primary'
          onClick={() => {
                Taro.pageScrollTo({scrollTop: 0, duration: 300});
                onClick?.();
            }}
          hoverClass='tap-active'
        >
            <XIcon name='carbon:arrow-up' size={20} className='text-white' />
        </View>
    );
};

export default BackToTop;

// frontend/app/vue/app/components/layout/BackToTop.vue
﻿<script setup lang="ts">
import { ref, onMounted, onUnmounted, watch } from 'vue'
import { cn } from '@/lib/utils'

const props = defineProps<{
  scrollThreshold?: number
  onClick?: () => void
  class?: string
  visible?: boolean
}>()

const showBackToTop = ref(false)

const handleScroll = () => {
  showBackToTop.value = window.scrollY > (props.scrollThreshold ?? 500)
}

onMounted(() => {
  window.addEventListener('scroll', handleScroll)
  handleScroll()
})

onUnmounted(() => {
  window.removeEventListener('scroll', handleScroll)
})

const isVisible = computed(() => props.visible !== undefined ? props.visible : showBackToTop.value)

const scrollToTop = () => {
  window.scrollTo({ top: 0, behavior: 'smooth' })
  props.onClick?.()
}
</script>

<template>
  <button
    v-if="isVisible"
    :class="cn(
      'fixed bottom-10 end-10 z-999 flex h-14 w-14 items-center justify-center',
      'rounded-full border-none bg-primary text-white cursor-pointer',
      'text-2xl shadow-lg transition-all duration-300',
      'hover:-translate-y-1 hover:shadow-xl hover:bg-primary/80',
      'active:-translate-y-0.5',
      props.class,
    )"
    aria-label="Back to top"
    @click="scrollToTop"
  >
    <XIcon icon="carbon:arrow-up" />
  </button>
</template>
