// frontend/app/react/src/components/layout/MobileNav.tsx
'use client';

import React, {useState, useEffect, useRef} from 'react';
import {useTranslations, useLocale} from 'next-intl';
import {Menu, User, Home, LogOut, Globe, Moon, Sun, Monitor, ChevronDown} from 'lucide-react';

import {Button} from '@/components/ui/button';
import {
    Sheet,
    SheetContent,
    SheetHeader,
    SheetTitle,
} from '@/components/ui/sheet';

import {XIcon} from '@/plugins/xicon';
import {useI18nRouter} from '@/i18n/helpers/useI18nRouter';
import {useI18n} from '@/i18n';
import {usePreferences} from '@/core/preferences';
import {fetchListNavigations} from '@/api/hooks/navigation';
import {useLanguageChangeEffect} from '@/hooks/useLanguageChangeEffect';
import {cn} from '@/lib/utils';
import {isSafeNavUrl} from '@/utils';

import {useAccessStore} from '@/store/core/access/store';
import {useAuth} from '@/api/hooks/auth';

import type {siteservicev1_Navigation, siteservicev1_NavigationItem} from '@/api/generated/app/service/v1';

/**
 * 手机端汉堡选单
 *
 * - 点击汉堡图标从右侧滑出全屏抽屉
 * - 包含主导航 + 用户操作 + 主题/语言切换
 * - 使用 shadcn Sheet (基于 @radix-ui/react-dialog)
 */
export default function MobileNav() {
    const t = useTranslations('navbar');
    const appT = useTranslations('app');
    const menuT = useTranslations('menu');
    const brandTitle = appT('title');

    const router = useI18nRouter();
    const locale = useLocale();
    const {theme: themePref, setThemeMode} = usePreferences();
    const {changeLocale} = useI18n();
    const accessStore = useAccessStore();
    const auth = useAuth();
    const currentMode = themePref.mode;

    const accessToken = accessStore.accessToken;
    const isLogin = !!accessToken && !accessStore.loginExpired;

    const [open, setOpen] = useState(false);
    const [navigationItems, setNavigationItems] = useState<siteservicev1_NavigationItem[]>([]);
    const [expandedId, setExpandedId] = useState<number | null>(null);

    useEffect(() => {
        let cancelled = false;
        (async () => {
            try {
                const res = await fetchListNavigations({
                    paging: {page: 1, pageSize: 10}
                }) as unknown as { items: siteservicev1_Navigation[]; total: number };

                if (cancelled) return;

                if (res.items?.length) {
                    const headerNav = res.items.find(nav =>
                        nav.location === 'HEADER' && nav.isActive === true
                    );
                    const items = headerNav?.items;
                    if (items && items.length > 0) {
                        setNavigationItems(items);
                    }
                }
            } catch (error) {
                console.error('[MobileNav] 加载导航失败:', error);
            }
        })();
        return () => { cancelled = true; };
    }, []);

    useLanguageChangeEffect(() => {
        fetchListNavigations({paging: {page: 1, pageSize: 10}})
            .then(res => {
                const navRes = res as unknown as { items: siteservicev1_Navigation[]; total: number };
                if (navRes.items?.length) {
                    const headerNav = navRes.items.find(nav =>
                        nav.location === 'HEADER' && nav.isActive === true
                    );
                    const items = headerNav?.items;
                    if (items && items.length > 0) {
                        setNavigationItems(items);
                    }
                }
            })
            .catch(error => console.error('[MobileNav] 重新加载导航失败:', error));
    }, {immediate: false, autoCleanup: true});

    const handleNavigate = (item: siteservicev1_NavigationItem) => {
        // 校验 URL 协议，拒绝 javascript:/data: 等危险协议（修复 AUD9-M1）
        if (!isSafeNavUrl(item.url)) {
            setOpen(false);
            return;
        }
        if (item.isOpenNewTab) {
            window.open(item.url, '_blank', 'noopener,noreferrer');
        } else if (item.url != null) {
            router.push(item.url);
        }
        setOpen(false);
    };

    const handleAction = (action: () => void) => {
        action();
        setOpen(false);
    };

    const themeIcon = currentMode === 'dark' ? <Moon className="h-4 w-4"/> :
        currentMode === 'light' ? <Sun className="h-4 w-4"/> :
            <Monitor className="h-4 w-4"/>;

    return (
        <>
            {/* 汉堡按钮 */}
            <Button
                variant="ghost"
                size="icon"
                aria-label="Open menu"
                onClick={() => setOpen(true)}
                className="md:hidden"
            >
                <Menu className="h-5 w-5"/>
            </Button>

            {/* 抽屉 */}
            <Sheet open={open} onOpenChange={setOpen}>
                <SheetContent side="right" className="flex w-full flex-col p-0 sm:max-w-sm">
                    {/* 顶部品牌区 */}
                    <SheetHeader className="border-b border-border px-5 py-4">
                        <div className="flex items-center gap-2">
                            {/* eslint-disable-next-line @next/next/no-img-element */}
                            <img src="/logo.png" alt="Logo" width={32} height={32} className="h-8 w-8"/>
                            <SheetTitle className="text-base font-bold text-primary">
                                {brandTitle}
                            </SheetTitle>
                        </div>
                    </SheetHeader>

                    {/* 滚动内容区 */}
                    <div className="flex-1 overflow-y-auto px-3 py-3">
                        {/* 主导航 */}
                        {navigationItems.length > 0 && (
                            <nav className="mb-3 space-y-0.5">
                                {navigationItems.map((item) => {
                                    const itemId = item.id ?? 0;
                                    const hasChildren = (item.children?.length ?? 0) > 0;
                                    const isExpanded = expandedId === itemId;

                                    return (
                                        <div key={itemId}>
                                            <button
                                                type="button"
                                                className={cn(
                                                    'flex w-full items-center justify-between gap-2 rounded-lg px-3 py-2.5 text-start text-sm font-medium',
                                                    'text-foreground/80 transition-colors',
                                                    'hover:bg-primary/10 hover:text-primary',
                                                )}
                                                onClick={() => {
                                                    if (hasChildren) {
                                                        setExpandedId(isExpanded ? null : itemId);
                                                    } else {
                                                        handleNavigate(item);
                                                    }
                                                }}
                                            >
                                                <span className="flex items-center gap-2">
                                                    {item.icon && <XIcon name={`carbon:${item.icon}`} size={16}/>}
                                                    <span>{item.title}</span>
                                                </span>
                                                {hasChildren && (
                                                    <ChevronDown className={cn('h-4 w-4 transition-transform', isExpanded && 'rotate-180')}/>
                                                )}
                                            </button>

                                            {/* 子菜单 */}
                                            {hasChildren && isExpanded && (
                                                <div className="ms-3 mt-0.5 space-y-0.5 border-s border-border ps-3">
                                                    {item.children!.map((child: siteservicev1_NavigationItem) => (
                                                        <button
                                                            key={child.id?.toString()}
                                                            type="button"
                                                            className="flex w-full items-center gap-2 rounded-md px-3 py-2 text-start text-sm text-foreground/70 transition-colors hover:bg-primary/10 hover:text-primary"
                                                            onClick={() => handleNavigate(child)}
                                                        >
                                                            {child.icon && <XIcon name={`carbon:${child.icon}`} size={14}/>}
                                                            <span>{child.title}</span>
                                                        </button>
                                                    ))}
                                                </div>
                                            )}
                                        </div>
                                    );
                                })}
                            </nav>
                        )}

                        {/* 分隔线 */}
                        <div className="my-2 border-t border-border"/>

                        {/* 用户操作 */}
                        <div className="space-y-0.5">
                            {isLogin ? (
                                <>
                                    <SheetNavItem
                                        icon={<Home className="h-4 w-4"/>}
                                        label={menuT('homepage')}
                                        onClick={() => handleAction(() => router.push('/user'))}
                                    />
                                    <SheetNavItem
                                        icon={<User className="h-4 w-4"/>}
                                        label={menuT('my_profile')}
                                        onClick={() => handleAction(() => router.push('/settings'))}
                                    />
                                    <SheetNavItem
                                        icon={<LogOut className="h-4 w-4"/>}
                                        label={menuT('logout')}
                                        onClick={() => handleAction(async () => {
                                            await auth.logout();
                                        })}
                                        destructive
                                    />
                                </>
                            ) : (
                                <>
                                    <SheetNavItem
                                        icon={<User className="h-4 w-4"/>}
                                        label={t('user.login')}
                                        onClick={() => handleAction(() => router.push('/login'))}
                                    />
                                    <SheetNavItem
                                        icon={<User className="h-4 w-4"/>}
                                        label={t('user.register')}
                                        onClick={() => handleAction(() => router.push('/register'))}
                                    />
                                </>
                            )}
                        </div>

                        {/* 分隔线 */}
                        <div className="my-2 border-t border-border"/>

                        {/* 语言切换 */}
                        <div className="mb-2 px-3 py-1 text-xs font-semibold text-muted-foreground">
                            <Globe className="me-1 inline h-3 w-3"/>
                            {t('language.title')}
                        </div>
                        <div className="space-y-0.5">
                            <SheetNavItem
                                label="简体中文"
                                onClick={() => handleAction(() => changeLocale('zh-CN'))}
                                active={locale === 'zh-CN'}
                            />
                            <SheetNavItem
                                label="English"
                                onClick={() => handleAction(() => changeLocale('en-US'))}
                                active={locale === 'en-US'}
                            />
                        </div>

                        {/* 分隔线 */}
                        <div className="my-2 border-t border-border"/>

                        {/* 主题切换 */}
                        <div className="mb-2 px-3 py-1 text-xs font-semibold text-muted-foreground">
                            {themeIcon}
                            <span className="ms-1">{t('theme.title') || 'Theme'}</span>
                        </div>
                        <div className="space-y-0.5">
                            <SheetNavItem
                                icon={<Sun className="h-4 w-4"/>}
                                label={t('theme.light')}
                                onClick={() => handleAction(() => setThemeMode('light'))}
                                active={currentMode === 'light'}
                            />
                            <SheetNavItem
                                icon={<Moon className="h-4 w-4"/>}
                                label={t('theme.dark')}
                                onClick={() => handleAction(() => setThemeMode('dark'))}
                                active={currentMode === 'dark'}
                            />
                            <SheetNavItem
                                icon={<Monitor className="h-4 w-4"/>}
                                label={t('theme.system')}
                                onClick={() => handleAction(() => setThemeMode('auto'))}
                                active={currentMode === 'auto'}
                            />
                        </div>
                    </div>
                </SheetContent>
            </Sheet>
        </>
    );
}

/** 抽屉内的导航项 */
function SheetNavItem({
    icon,
    label,
    onClick,
    active,
    destructive,
}: {
    icon?: React.ReactNode;
    label: React.ReactNode;
    onClick: () => void;
    active?: boolean;
    destructive?: boolean;
}) {
    return (
        <button
            type="button"
            className={cn(
                'flex w-full items-center gap-2 rounded-lg px-3 py-2.5 text-start text-sm font-medium transition-colors',
                active
                    ? 'bg-primary/10 text-primary'
                    : destructive
                        ? 'text-destructive hover:bg-destructive/10'
                        : 'text-foreground/80 hover:bg-primary/10 hover:text-primary',
            )}
            onClick={onClick}
        >
            {icon}
            <span>{label}</span>
        </button>
    );
}

// frontend/app/vue/app/components/layout/MobileNav.vue
<script setup lang="ts">
import { ref, onMounted, onUnmounted, watch } from 'vue'
import { XIcon } from '@/plugins/xicon'
import { useLanguageChangeEffect } from '@/hooks/use-language-change-effect'
import { usePreferences } from '@/core/preferences/use-preferences'
import { useAccessStore } from '@/stores/modules/core/access.state'
import { useAuthStore } from '@/stores/modules/app/auth.state'
import { fetchListNavigation } from '@/api/composables/navigation'
import { cn } from '@/lib/utils'

// @ts-ignore
import type { siteservicev1_NavigationItem } from '@/api/generated/app/service/v1'

const { t } = useI18n()
const localePath = useLocalePath()
const switchLocalePath = useSwitchLocalePath()
const { locale } = useI18n()
const { themePreferences: themePref, setTheme: setThemeMode } = usePreferences()
const currentMode = computed(() => themePref.value.mode)
const accessStore = useAccessStore()
const authStore = useAuthStore()

const isLogin = computed(() => {
  const token = accessStore.accessToken
  return !!token?.value && !accessStore.loginExpired
})

const open = ref(false)
const navigationItems = ref<siteservicev1_NavigationItem[]>([])
const expandedId = ref<number | null>(null)

const loadNav = async () => {
  try {
    const res = await fetchListNavigation({
      paging: { page: 1, pageSize: 10 },
    }) as any

    if (res.items?.length) {
      const headerNav = res.items.find((nav: any) =>
        nav.location === 'HEADER' && nav.isActive === true
      )
      const items = headerNav?.items
      if (items && items.length > 0) {
        navigationItems.value = items
      }
    }
  } catch (error) {
    console.error('[MobileNav] 加载导航失败:', error)
  }
}

onMounted(loadNav)

useLanguageChangeEffect(() => {
  fetchListNavigation({ paging: { page: 1, pageSize: 10 } })
    .then((res: any) => {
      if (res.items?.length) {
        const headerNav = res.items.find((nav: any) =>
          nav.location === 'HEADER' && nav.isActive === true
        )
        const items = headerNav?.items
        if (items && items.length > 0) {
          navigationItems.value = items
        }
      }
    })
    .catch((error: any) => console.error('[MobileNav] 重新加载导航失败:', error))
}, { immediate: false, autoCleanup: true })

const handleNavigate = (item: siteservicev1_NavigationItem) => {
  const url = item.url
  if (!url) {
    open.value = false
    return
  }
  // 仅允许相对路径或 http(s) 外链，避免 javascript:/data: 等协议注入
  const isExternal = /^https?:\/\//i.test(url)
  if (item.isOpenNewTab) {
    if (isExternal) {
      window.open(url, '_blank', 'noopener,noreferrer')
    } else {
      navigateTo(localePath(url))
    }
  } else {
    navigateTo(localePath(url))
  }
  open.value = false
}

const handleAction = (action: () => void) => {
  action()
  open.value = false
}
</script>

<template>
  <!-- 汉堡按钮 -->
  <UiButton variant="ghost" size="icon" aria-label="Open menu" class="md:hidden" @click="open = true">
    <XIcon icon="lucide:menu" width="20" height="20" />
  </UiButton>

  <!-- 抽屉 -->
  <UiSheet :open="open" @update:open="open = $event">
    <UiSheetContent side="right" class="flex w-full flex-col p-0 sm:max-w-sm">
      <!-- 顶部品牌区 -->
      <UiSheetHeader class="border-b border-border px-5 py-4">
        <div class="flex items-center gap-2">
          <img src="/logo.png" alt="Logo" width="32" height="32" class="h-8 w-8" />
          <UiSheetTitle class="text-base font-bold text-primary">
            {{ t('app.title') }}
          </UiSheetTitle>
        </div>
      </UiSheetHeader>

      <!-- 滚动内容区 -->
      <div class="flex-1 overflow-y-auto px-3 py-3">
        <!-- 主导航 -->
        <nav v-if="navigationItems.length > 0" class="mb-3 space-y-0.5">
          <div v-for="item in navigationItems" :key="item.id ?? 0">
            <button
              type="button"
              :class="cn(
                'flex w-full items-center justify-between gap-2 rounded-lg px-3 py-2.5 text-start text-sm font-medium',
                'text-foreground/80 transition-colors',
                'hover:bg-primary/10 hover:text-primary',
              )"
              @click="() => {
                const hasChildren = (item.children?.length ?? 0) > 0
                if (hasChildren) {
                  expandedId = expandedId === (item.id ?? 0) ? null : (item.id ?? 0)
                } else {
                  handleNavigate(item)
                }
              }"
            >
              <span class="flex items-center gap-2">
                <XIcon v-if="item.icon" :icon="`carbon:${item.icon}`" :size="16" />
                <span>{{ item.title }}</span>
              </span>
              <XIcon                 v-if="(item.children?.length ?? 0) > 0"
                icon="lucide:chevron-down"
                width="16" height="16"
                :class="cn('transition-transform', expandedId === (item.id ?? 0) && 'rotate-180')"
              />
            </button>

            <!-- 子菜单 -->
            <div
              v-if="(item.children?.length ?? 0) > 0 && expandedId === (item.id ?? 0)"
              class="ms-3 mt-0.5 space-y-0.5 border-s border-border ps-3"
            >
              <button
                v-for="child in item.children"
                :key="child.id?.toString()"
                type="button"
                class="flex w-full items-center gap-2 rounded-md px-3 py-2 text-start text-sm text-foreground/70 transition-colors hover:bg-primary/10 hover:text-primary"
                @click="handleNavigate(child)"
              >
                <XIcon v-if="child.icon" :icon="`carbon:${child.icon}`" :size="14" />
                <span>{{ child.title }}</span>
              </button>
            </div>
          </div>
        </nav>

        <!-- 分隔线 -->
        <div class="my-2 border-t border-border" />

        <!-- 用户操作 -->
        <div class="space-y-0.5">
          <template v-if="isLogin">
            <button
              type="button"
              class="flex w-full items-center gap-2 rounded-lg px-3 py-2.5 text-start text-sm font-medium text-foreground/80 transition-colors hover:bg-primary/10 hover:text-primary"
              @click="handleAction(() => navigateTo(localePath('/user')))"
            >
              <XIcon icon="lucide:home" width="16" height="16" />
              <span>{{ t('menu.homepage') }}</span>
            </button>
            <button
              type="button"
              class="flex w-full items-center gap-2 rounded-lg px-3 py-2.5 text-start text-sm font-medium text-foreground/80 transition-colors hover:bg-primary/10 hover:text-primary"
              @click="handleAction(() => navigateTo(localePath('/settings')))"
            >
              <XIcon icon="lucide:user" width="16" height="16" />
              <span>{{ t('menu.my_profile') }}</span>
            </button>
            <button
              type="button"
              class="flex w-full items-center gap-2 rounded-lg px-3 py-2.5 text-start text-sm font-medium text-destructive hover:bg-destructive/10"
              @click="handleAction(async () => { await authStore.logout() })"
            >
              <XIcon icon="lucide:log-out" width="16" height="16" />
              <span>{{ t('menu.logout') }}</span>
            </button>
          </template>
          <template v-else>
            <button
              type="button"
              class="flex w-full items-center gap-2 rounded-lg px-3 py-2.5 text-start text-sm font-medium text-foreground/80 transition-colors hover:bg-primary/10 hover:text-primary"
              @click="handleAction(() => navigateTo(localePath('/login')))"
            >
              <XIcon icon="lucide:user" width="16" height="16" />
              <span>{{ t('navbar.user.login') }}</span>
            </button>
            <button
              type="button"
              class="flex w-full items-center gap-2 rounded-lg px-3 py-2.5 text-start text-sm font-medium text-foreground/80 transition-colors hover:bg-primary/10 hover:text-primary"
              @click="handleAction(() => navigateTo(localePath('/register')))"
            >
              <XIcon icon="lucide:user" width="16" height="16" />
              <span>{{ t('navbar.user.register') }}</span>
            </button>
          </template>
        </div>

        <!-- 分隔线 -->
        <div class="my-2 border-t border-border" />

        <!-- 语言切换 -->
        <div class="mb-2 px-3 py-1 text-xs font-semibold text-muted-foreground">
          <XIcon icon="lucide:globe" width="12" height="12" class="me-1 inline" />
          {{ t('navbar.language.title') }}
        </div>
        <div class="space-y-0.5">
          <button
            type="button"
            :class="cn(
              'flex w-full items-center gap-2 rounded-lg px-3 py-2.5 text-start text-sm font-medium transition-colors',
              locale === 'zh-CN' ? 'bg-primary/10 text-primary' : 'text-foreground/80 hover:bg-primary/10 hover:text-primary',
            )"
            @click="handleAction(() => navigateTo(switchLocalePath('zh-CN')))"
          >
            <span>简体中文</span>
          </button>
          <button
            type="button"
            :class="cn(
              'flex w-full items-center gap-2 rounded-lg px-3 py-2.5 text-start text-sm font-medium transition-colors',
              locale === 'en-US' ? 'bg-primary/10 text-primary' : 'text-foreground/80 hover:bg-primary/10 hover:text-primary',
            )"
            @click="handleAction(() => navigateTo(switchLocalePath('en-US')))"
          >
            <span>English</span>
          </button>
          <button
            type="button"
            :class="cn(
              'flex w-full items-center gap-2 rounded-lg px-3 py-2.5 text-start text-sm font-medium transition-colors',
              locale === 'ar' ? 'bg-primary/10 text-primary' : 'text-foreground/80 hover:bg-primary/10 hover:text-primary',
            )"
            @click="handleAction(() => navigateTo(switchLocalePath('ar')))"
          >
            <span>العربية</span>
          </button>
        </div>

        <!-- 分隔线 -->
        <div class="my-2 border-t border-border" />

        <!-- 主题切换 -->
        <div class="mb-2 px-3 py-1 text-xs font-semibold text-muted-foreground">
          <XIcon             :icon="currentMode === 'dark' ? 'lucide:moon' : currentMode === 'light' ? 'lucide:sun' : 'lucide:monitor'"
            width="16" height="16"
          />
          <span class="ms-1">{{ t('navbar.theme.title') || 'Theme' }}</span>
        </div>
        <div class="space-y-0.5">
          <button
            v-for="mode in [
              { key: 'light', icon: 'lucide:sun', label: t('navbar.theme.light') },
              { key: 'dark', icon: 'lucide:moon', label: t('navbar.theme.dark') },
              { key: 'auto', icon: 'lucide:monitor', label: t('navbar.theme.system') },
            ]"
            :key="mode.key"
            type="button"
            :class="cn(
              'flex w-full items-center gap-2 rounded-lg px-3 py-2.5 text-start text-sm font-medium transition-colors',
              currentMode === mode.key ? 'bg-primary/10 text-primary' : 'text-foreground/80 hover:bg-primary/10 hover:text-primary',
            )"
            @click="handleAction(() => setThemeMode(mode.key as any))"
          >
            <XIcon :icon="mode.icon" width="16" height="16" />
            <span>{{ mode.label }}</span>
          </button>
        </div>
      </div>
    </UiSheetContent>
  </UiSheet>
</template>
