// frontend/app/vue/app/components/home/PopularTagsSection.vue
﻿<script setup lang="ts">
import { ref, onMounted, onUnmounted } from 'vue'
import { XIcon } from '@/plugins/xicon'
import { fetchListTag } from '@/api/composables/tag'

const { t } = useI18n()
const localePath = useLocalePath()

interface TagItem {
  id: number
  name: string
  color: string
  postCount: number
}

const loading = ref(true)
const displayTags = ref<TagItem[]>([])
const hoveredId = ref<number | null>(null)

let abortController: AbortController | null = null

onMounted(async () => {
  loading.value = true
  try {
    const res = await fetchListTag({
      paging: { page: 1, pageSize: 6 },
      formValues: { status: 'TAG_STATUS_ACTIVE', isFeatured: true },
    }) as any

    const tagItems = res.items || []
    displayTags.value = tagItems
      .filter((tag: any) => tag.id !== undefined)
      .map((tag: any, index: number) => ({
        id: tag.id,
        name: tag.translations?.[0]?.name || t('page.tags.tag_untitled'),
        color: tag.color || `hsl(${(index * 67) % 360}, 70%, 55%)`,
        postCount: tag.postCount || 0,
      }))
  } catch (error) {
    console.error('Failed to load tags:', error)
  } finally {
    loading.value = false
  }
})

onUnmounted(() => { abortController?.abort() })
</script>

<template>
  <section class="w-full max-w-300 mx-auto px-8 py-12 max-md:px-4">
    <div class="mb-8 flex items-center justify-between">
      <h2 class="flex items-center gap-2 text-2xl font-extrabold tracking-tight text-foreground max-md:text-xl">
        <XIcon icon="carbon:fire" :size="28" class="me-2 text-primary" />
        {{ t('page.tags.popular_tags') }}
      </h2>
      <UiButton variant="ghost" @click="navigateTo(localePath('/tag'))">
        {{ t('page.tags.view_all') }} →
      </UiButton>
    </div>
    <div class="w-full">
      <!-- Loading -->
      <div v-if="loading" class="flex flex-wrap justify-center gap-3">
        <div v-for="i in 6" :key="i" class="h-10 w-28">
          <UiSkeleton class="h-full w-full rounded-full" />
        </div>
      </div>
      <!-- Tags -->
      <div v-else class="flex flex-wrap justify-center gap-3 max-md:gap-2">
        <button
          v-for="tag in displayTags"
          :key="tag.id"
          class="group flex cursor-pointer items-center gap-2 rounded-full border-2 px-5 py-2.5 text-sm font-semibold transition-all duration-300 hover:-translate-y-0.5 hover:shadow-lg max-md:px-4 max-md:py-2 max-md:text-xs"
          :style="hoveredId === tag.id ? {
            backgroundColor: tag.color,
            color: '#ffffff',
            borderColor: tag.color,
            boxShadow: `0 8px 24px -8px ${tag.color}80`,
          } : {
            backgroundColor: `${tag.color}12`,
            color: tag.color,
            borderColor: `${tag.color}40`,
          }"
          @mouseenter="hoveredId = tag.id"
          @mouseleave="hoveredId = null"
          @click="navigateTo(localePath(`/tag/${tag.id}`))"
        >
          <span class="h-2 w-2 rounded-full transition-all duration-300" :style="{ backgroundColor: hoveredId === tag.id ? '#fff' : tag.color }" />
          <span class="truncate tracking-tight">{{ tag.name }}</span>
          <span
            v-if="tag.postCount > 0"
            class="rounded-full px-2 py-0.5 text-[10px] font-bold leading-none transition-colors duration-300"
            :style="hoveredId === tag.id ? { backgroundColor: 'rgba(255,255,255,0.25)', color: '#fff' } : { backgroundColor: `${tag.color}25` }"
          >
            {{ tag.postCount }}
          </span>
        </button>
      </div>
    </div>
  </section>
</template>

// frontend/app/taro/src/components/home/PopularTagsSection.tsx
import {View, Text} from '@tarojs/components';
import {useState, useEffect, useCallback, useRef} from 'react';
import {Skeleton} from '@/components/ui/skeleton';
import {useTranslations} from '@/lib/next-intl-compat';
import {XIcon} from '@/plugins/xicon';
import {fetchListTags} from '@/api/hooks/tag';
import {useI18nRouter} from '@/i18n/helpers/useI18nRouter';
import {contentservicev1_ListTagResponse} from '@/api/generated/app/service/v1';

interface TagItem {
    id: number;
    name: string;
    color: string;
    postCount: number;
}

/** 预定义标签色板，避免 HSL 在小程序端兼容性问题 */
const TAG_COLORS = [
    '#006be6', '#00b42a', '#ff7d00', '#f53f3f',
    '#722ed1', '#13c2c2', '#eb2f96', '#faad14',
];

/**
 * 首页「热门标签」区块
 * - flex wrap 流式布局
 * - 显示最多 6 个标签
 */
export default function PopularTagsSection() {
    const t = useTranslations('page.tags');
    const router = useI18nRouter();
    const [loading, setLoading] = useState(false);
    const [displayTags, setDisplayTags] = useState<TagItem[]>([]);
    const abortRef = useRef<AbortController | null>(null);

    const loadPopularTags = useCallback(async () => {
        if (abortRef.current) abortRef.current.abort();
        abortRef.current = new AbortController();
        setLoading(true);
        try {
            const res = await fetchListTags({
                paging: {page: 1, pageSize: 6},
                formValues: {status: 'TAG_STATUS_ACTIVE', isFeatured: true},
            }) as unknown as contentservicev1_ListTagResponse;
            const tagItems = (res.items || [])
                .filter(tag => tag.id !== undefined)
                .map((tag, index) => ({
                    id: tag.id!,
                    name: tag.translations?.[0]?.name || t('tag_untitled'),
                    color: tag.color || TAG_COLORS[index % TAG_COLORS.length],
                    postCount: tag.postCount || 0,
                }));
            setDisplayTags(tagItems);
        } catch (error) {
            console.error('Failed to load tags:', error);
            setDisplayTags([]);
        } finally {
            setLoading(false);
        }
    }, [t]);

    useEffect(() => {
        loadPopularTags();
        return () => { abortRef.current?.abort(); };
    }, []);

    return (
        <View className='w-full'>
            {/* 标题行 */}
            <View className='flex items-center justify-between mb-[32rpx]'>
                <View className='flex items-center gap-[8rpx]'>
                    <XIcon name='carbon:fire' size={20} className='text-primary' />
                    <Text className='text-card-title font-bold text-textMain'>
                        {t('popular_tags')}
                    </Text>
                </View>
                <View
                  className='px-[24rpx] py-[12rpx] rounded-full flex items-center justify-center'
                  style={{
                      backgroundColor: 'rgba(0,107,230,0.08)',
                  }}
                  onClick={() => router.push('/tag')}
                  hoverClass='tap-active'
                >
                    <Text className='text-tips font-medium text-primary'>{t('view_all')} →</Text>
                </View>
            </View>

            {loading ? (
                <View className='flex flex-wrap gap-[16rpx]'>
                    {Array.from({length: 6}).map((_, i) => (
                        <View key={i} className='h-[64rpx] w-[160rpx]'>
                            <Skeleton className='h-full w-full rounded-full' />
                        </View>
                    ))}
                </View>
            ) : displayTags.length > 0 ? (
                <View className='flex flex-wrap gap-[16rpx]'>
                    {displayTags.map((tag) => (
                        <View
                          key={tag.id}
                          className='flex items-center gap-[8rpx] rounded-full px-[24rpx] py-[12rpx] min-h-[64rpx]'
                          style={{
                                backgroundColor: `${tag.color}14`,
                                borderWidth: '2rpx',
                                borderStyle: 'solid',
                                borderColor: `${tag.color}40`,
                            }}
                          onClick={() => router.push(`/tag/detail?id=${tag.id}`)}
                          hoverClass='tap-active'
                        >
                            <View
                              className='w-[12rpx] h-[12rpx] rounded-full'
                              style={{backgroundColor: tag.color}}
                            />
                            <Text className='text-desc font-semibold' style={{color: tag.color}}>
                                {tag.name}
                            </Text>
                            {tag.postCount > 0 && (
                                <Text className='text-tips' style={{color: tag.color}}>
                                    {tag.postCount}
                                </Text>
                            )}
                        </View>
                    ))}
                </View>
            ) : null}
        </View>
    );
}
