// frontend/app/vue/app/components/ui/app-empty/AppEmpty.vue
<script setup lang="ts">
import { cn } from '@/lib/utils'

const props = defineProps<{
  variant?: 'default' | 'error' | 'noData'
  inContainer?: boolean
  description?: string
  class?: string
}>()
</script>

<template>
  <div :class="cn('flex w-full items-center justify-center gap-4 py-12 px-5', props.inContainer && 'my-20', props.class)">
    <div class="opacity-50">
      <slot name="image">
        <XIcon icon="lucide:inbox" width="64" height="64" class="text-muted-foreground" />
      </slot>
    </div>
    <p v-if="description" class="text-sm text-muted-foreground">{{ description }}</p>
    <p v-else-if="$slots.default" class="text-sm text-muted-foreground">
      <slot />
    </p>
  </div>
</template>

// frontend/app/taro/src/components/ui/AppEmpty.tsx
import React from 'react';
import {View, Text} from '@tarojs/components';
import {XIcon} from '@/plugins/xicon';
import {cn} from '@/lib/utils';

interface AppEmptyProps {
    variant?: 'default' | 'error' | 'noData';
    inContainer?: boolean;
    image?: React.ReactNode;
    description?: React.ReactNode;
    className?: string;
    style?: React.CSSProperties;
}

export const AppEmpty: React.FC<AppEmptyProps> = ({
    inContainer = false,
    image,
    description,
    className,
    style,
}) => {
    const defaultIcon = image || (
        <XIcon name='carbon:inbox' size={48} className='text-textWeak' />
    );

    return (
        <View
          className={cn(
                'flex w-full flex-col items-center justify-center gap-[24rpx] py-[96rpx] px-[24rpx]',
                inContainer && 'my-[120rpx]',
                className,
            )}
          style={style}
        >
            <View className='opacity-50'>{defaultIcon}</View>
            {description && (
                <Text className='text-desc text-textThird'>{description}</Text>
            )}
        </View>
    );
};

export default AppEmpty;
