// frontend/app/vue/app/pages/privacy.vue
<script setup lang="ts">
const { t } = useI18n()

useHead({ title: t('page.legal.privacy.title') })
</script>

<template>
  <LayoutLegalPage
    icon="carbon:locked"
    :title="t('page.legal.privacy.title')"
    :description="t('page.legal.privacy.description')"
    :items="[t('page.legal.privacy.item_1'), t('page.legal.privacy.item_2'), t('page.legal.privacy.item_3')]"
  />
</template>

// frontend/app/react/src/app/[locale]/privacy/page.tsx
'use client';

import {useTranslations} from 'next-intl';
import LegalPage from '@/components/layout/LegalPage';

export default function PrivacyPage() {
    const t = useTranslations('page.legal.privacy');

    return (
        <LegalPage
            icon="carbon:locked"
            title={t('title')}
            description={t('description')}
            items={[t('item_1'), t('item_2'), t('item_3')]}
        />
    );
}
