// frontend/app/vue/app/components/layout/LegalPage.vue
<script setup lang="ts">
import { cn } from '@/lib/utils'

const props = defineProps<{
  icon: string
  title: string
  description: string
  items: string[]
}>()
</script>

<template>
  <div class="w-full">
    <LayoutPageHero
      :title="title"
      :description="description"
      :icon="icon"
      size="sm"
    />

    <section class="w-full py-12 max-md:py-8">
      <div class="mx-auto max-w-4xl px-4">
        <div :class="cn(
          'rounded-2xl border border-border bg-card p-8 md:p-10',
          'shadow-[0_20px_50px_rgba(0,0,0,0.15)]',
          'transition-all duration-300',
          'hover:border-primary/20',
        )">
          <ul class="space-y-5">
            <li
              v-for="(item, index) in items"
              :key="index"
              class="flex items-start gap-4 text-base leading-relaxed text-foreground max-md:text-sm"
            >
              <span :class="cn(
                'shrink-0 font-mono text-sm font-bold tabular-nums',
                'text-primary',
                'mt-0.5 min-w-[2rem]',
              )">
                {{ String(index + 1).padStart(2, '0') }}.
              </span>
              <span>{{ item }}</span>
            </li>
          </ul>
        </div>
      </div>
    </section>
  </div>
</template>

// frontend/app/taro/src/components/layout/LegalPage.tsx
import {View, Text} from '@tarojs/components';
import {XIcon} from '@/plugins/xicon';

interface LegalPageProps {
    icon: string;
    title: string;
    description: string;
    items: string[];
}

export default function LegalPage({icon, title, description, items}: LegalPageProps) {
    return (
        <View className='w-full bg-pageBg'>
            {/* 页面标题栏 */}
            <View className='bg-cardBg px-[24rpx] py-[32rpx] border-b-[1rpx] border-splitLine'>
                <View className='flex items-center gap-[16rpx] mb-[16rpx]'>
                    <XIcon name={icon} size={24} className='text-primary' />
                    <Text className='text-title font-bold text-textMain'>{title}</Text>
                </View>
                <Text className='text-desc text-textSec'>{description}</Text>
            </View>

            {/* 内容列表 */}
            <View className='px-[24rpx] py-[32rpx]'>
                <View className='rounded bg-cardBg p-[24rpx]'>
                    {items.map((item, index) => (
                        <View
                          key={index}
                          className='flex items-start gap-[16rpx] py-[16rpx]'
                        >
                            <Text className='shrink-0 text-desc font-bold text-primary min-w-[48rpx]'>
                                {String(index + 1).padStart(2, '0')}.
                            </Text>
                            <Text className='text-body text-textMain leading-relaxed'>{item}</Text>
                        </View>
                    ))}
                </View>
            </View>
        </View>
    );
}
