// frontend/app/vue/app/components/layout/MobileNav.vue
<script setup lang="ts">
import { ref, onMounted, onUnmounted, watch } from 'vue'
import { XIcon } from '@/plugins/xicon'
import { useLanguageChangeEffect } from '@/hooks/use-language-change-effect'
import { usePreferences } from '@/core/preferences/use-preferences'
import { useAccessStore } from '@/stores/modules/core/access.state'
import { useAuthStore } from '@/stores/modules/app/auth.state'
import { fetchListNavigation } from '@/api/composables/navigation'
import { cn } from '@/lib/utils'

// @ts-ignore
import type { siteservicev1_NavigationItem } from '@/api/generated/app/service/v1'

const { t } = useI18n()
const localePath = useLocalePath()
const switchLocalePath = useSwitchLocalePath()
const { locale } = useI18n()
const { themePreferences: themePref, setTheme: setThemeMode } = usePreferences()
const currentMode = computed(() => themePref.value.mode)
const accessStore = useAccessStore()
const authStore = useAuthStore()

const isLogin = computed(() => {
  const token = accessStore.accessToken
  return !!token?.value && !accessStore.loginExpired
})

const open = ref(false)
const navigationItems = ref<siteservicev1_NavigationItem[]>([])
const expandedId = ref<number | null>(null)

const loadNav = async () => {
  try {
    const res = await fetchListNavigation({
      paging: { page: 1, pageSize: 10 },
    }) as any

    if (res.items?.length) {
      const headerNav = res.items.find((nav: any) =>
        nav.location === 'HEADER' && nav.isActive === true
      )
      const items = headerNav?.items
      if (items && items.length > 0) {
        navigationItems.value = items
      }
    }
  } catch (error) {
    console.error('[MobileNav] 加载导航失败:', error)
  }
}

onMounted(loadNav)

useLanguageChangeEffect(() => {
  fetchListNavigation({ paging: { page: 1, pageSize: 10 } })
    .then((res: any) => {
      if (res.items?.length) {
        const headerNav = res.items.find((nav: any) =>
          nav.location === 'HEADER' && nav.isActive === true
        )
        const items = headerNav?.items
        if (items && items.length > 0) {
          navigationItems.value = items
        }
      }
    })
    .catch((error: any) => console.error('[MobileNav] 重新加载导航失败:', error))
}, { immediate: false, autoCleanup: true })

const handleNavigate = (item: siteservicev1_NavigationItem) => {
  const url = item.url
  if (!url) {
    open.value = false
    return
  }
  // 仅允许相对路径或 http(s) 外链，避免 javascript:/data: 等协议注入
  const isExternal = /^https?:\/\//i.test(url)
  if (item.isOpenNewTab) {
    if (isExternal) {
      window.open(url, '_blank', 'noopener,noreferrer')
    } else {
      navigateTo(localePath(url))
    }
  } else {
    navigateTo(localePath(url))
  }
  open.value = false
}

const handleAction = (action: () => void) => {
  action()
  open.value = false
}
</script>

<template>
  <!-- 汉堡按钮 -->
  <UiButton variant="ghost" size="icon" aria-label="Open menu" class="md:hidden" @click="open = true">
    <XIcon icon="lucide:menu" width="20" height="20" />
  </UiButton>

  <!-- 抽屉 -->
  <UiSheet :open="open" @update:open="open = $event">
    <UiSheetContent side="right" class="flex w-full flex-col p-0 sm:max-w-sm">
      <!-- 顶部品牌区 -->
      <UiSheetHeader class="border-b border-border px-5 py-4">
        <div class="flex items-center gap-2">
          <img src="/logo.png" alt="Logo" width="32" height="32" class="h-8 w-8" />
          <UiSheetTitle class="text-base font-bold text-primary">
            {{ t('app.title') }}
          </UiSheetTitle>
        </div>
      </UiSheetHeader>

      <!-- 滚动内容区 -->
      <div class="flex-1 overflow-y-auto px-3 py-3">
        <!-- 主导航 -->
        <nav v-if="navigationItems.length > 0" class="mb-3 space-y-0.5">
          <div v-for="item in navigationItems" :key="item.id ?? 0">
            <button
              type="button"
              :class="cn(
                'flex w-full items-center justify-between gap-2 rounded-lg px-3 py-2.5 text-start text-sm font-medium',
                'text-foreground/80 transition-colors',
                'hover:bg-primary/10 hover:text-primary',
              )"
              @click="() => {
                const hasChildren = (item.children?.length ?? 0) > 0
                if (hasChildren) {
                  expandedId = expandedId === (item.id ?? 0) ? null : (item.id ?? 0)
                } else {
                  handleNavigate(item)
                }
              }"
            >
              <span class="flex items-center gap-2">
                <XIcon v-if="item.icon" :icon="`carbon:${item.icon}`" :size="16" />
                <span>{{ item.title }}</span>
              </span>
              <XIcon                 v-if="(item.children?.length ?? 0) > 0"
                icon="lucide:chevron-down"
                width="16" height="16"
                :class="cn('transition-transform', expandedId === (item.id ?? 0) && 'rotate-180')"
              />
            </button>

            <!-- 子菜单 -->
            <div
              v-if="(item.children?.length ?? 0) > 0 && expandedId === (item.id ?? 0)"
              class="ms-3 mt-0.5 space-y-0.5 border-s border-border ps-3"
            >
              <button
                v-for="child in item.children"
                :key="child.id?.toString()"
                type="button"
                class="flex w-full items-center gap-2 rounded-md px-3 py-2 text-start text-sm text-foreground/70 transition-colors hover:bg-primary/10 hover:text-primary"
                @click="handleNavigate(child)"
              >
                <XIcon v-if="child.icon" :icon="`carbon:${child.icon}`" :size="14" />
                <span>{{ child.title }}</span>
              </button>
            </div>
          </div>
        </nav>

        <!-- 分隔线 -->
        <div class="my-2 border-t border-border" />

        <!-- 用户操作 -->
        <div class="space-y-0.5">
          <template v-if="isLogin">
            <button
              type="button"
              class="flex w-full items-center gap-2 rounded-lg px-3 py-2.5 text-start text-sm font-medium text-foreground/80 transition-colors hover:bg-primary/10 hover:text-primary"
              @click="handleAction(() => navigateTo(localePath('/user')))"
            >
              <XIcon icon="lucide:home" width="16" height="16" />
              <span>{{ t('menu.homepage') }}</span>
            </button>
            <button
              type="button"
              class="flex w-full items-center gap-2 rounded-lg px-3 py-2.5 text-start text-sm font-medium text-foreground/80 transition-colors hover:bg-primary/10 hover:text-primary"
              @click="handleAction(() => navigateTo(localePath('/settings')))"
            >
              <XIcon icon="lucide:user" width="16" height="16" />
              <span>{{ t('menu.my_profile') }}</span>
            </button>
            <button
              type="button"
              class="flex w-full items-center gap-2 rounded-lg px-3 py-2.5 text-start text-sm font-medium text-destructive hover:bg-destructive/10"
              @click="handleAction(async () => { await authStore.logout() })"
            >
              <XIcon icon="lucide:log-out" width="16" height="16" />
              <span>{{ t('menu.logout') }}</span>
            </button>
          </template>
          <template v-else>
            <button
              type="button"
              class="flex w-full items-center gap-2 rounded-lg px-3 py-2.5 text-start text-sm font-medium text-foreground/80 transition-colors hover:bg-primary/10 hover:text-primary"
              @click="handleAction(() => navigateTo(localePath('/login')))"
            >
              <XIcon icon="lucide:user" width="16" height="16" />
              <span>{{ t('navbar.user.login') }}</span>
            </button>
            <button
              type="button"
              class="flex w-full items-center gap-2 rounded-lg px-3 py-2.5 text-start text-sm font-medium text-foreground/80 transition-colors hover:bg-primary/10 hover:text-primary"
              @click="handleAction(() => navigateTo(localePath('/register')))"
            >
              <XIcon icon="lucide:user" width="16" height="16" />
              <span>{{ t('navbar.user.register') }}</span>
            </button>
          </template>
        </div>

        <!-- 分隔线 -->
        <div class="my-2 border-t border-border" />

        <!-- 语言切换 -->
        <div class="mb-2 px-3 py-1 text-xs font-semibold text-muted-foreground">
          <XIcon icon="lucide:globe" width="12" height="12" class="me-1 inline" />
          {{ t('navbar.language.title') }}
        </div>
        <div class="space-y-0.5">
          <button
            type="button"
            :class="cn(
              'flex w-full items-center gap-2 rounded-lg px-3 py-2.5 text-start text-sm font-medium transition-colors',
              locale === 'zh-CN' ? 'bg-primary/10 text-primary' : 'text-foreground/80 hover:bg-primary/10 hover:text-primary',
            )"
            @click="handleAction(() => navigateTo(switchLocalePath('zh-CN')))"
          >
            <span>简体中文</span>
          </button>
          <button
            type="button"
            :class="cn(
              'flex w-full items-center gap-2 rounded-lg px-3 py-2.5 text-start text-sm font-medium transition-colors',
              locale === 'en-US' ? 'bg-primary/10 text-primary' : 'text-foreground/80 hover:bg-primary/10 hover:text-primary',
            )"
            @click="handleAction(() => navigateTo(switchLocalePath('en-US')))"
          >
            <span>English</span>
          </button>
          <button
            type="button"
            :class="cn(
              'flex w-full items-center gap-2 rounded-lg px-3 py-2.5 text-start text-sm font-medium transition-colors',
              locale === 'ar' ? 'bg-primary/10 text-primary' : 'text-foreground/80 hover:bg-primary/10 hover:text-primary',
            )"
            @click="handleAction(() => navigateTo(switchLocalePath('ar')))"
          >
            <span>العربية</span>
          </button>
        </div>

        <!-- 分隔线 -->
        <div class="my-2 border-t border-border" />

        <!-- 主题切换 -->
        <div class="mb-2 px-3 py-1 text-xs font-semibold text-muted-foreground">
          <XIcon             :icon="currentMode === 'dark' ? 'lucide:moon' : currentMode === 'light' ? 'lucide:sun' : 'lucide:monitor'"
            width="16" height="16"
          />
          <span class="ms-1">{{ t('navbar.theme.title') || 'Theme' }}</span>
        </div>
        <div class="space-y-0.5">
          <button
            v-for="mode in [
              { key: 'light', icon: 'lucide:sun', label: t('navbar.theme.light') },
              { key: 'dark', icon: 'lucide:moon', label: t('navbar.theme.dark') },
              { key: 'auto', icon: 'lucide:monitor', label: t('navbar.theme.system') },
            ]"
            :key="mode.key"
            type="button"
            :class="cn(
              'flex w-full items-center gap-2 rounded-lg px-3 py-2.5 text-start text-sm font-medium transition-colors',
              currentMode === mode.key ? 'bg-primary/10 text-primary' : 'text-foreground/80 hover:bg-primary/10 hover:text-primary',
            )"
            @click="handleAction(() => setThemeMode(mode.key as any))"
          >
            <XIcon :icon="mode.icon" width="16" height="16" />
            <span>{{ mode.label }}</span>
          </button>
        </div>
      </div>
    </UiSheetContent>
  </UiSheet>
</template>

// frontend/app/taro/src/components/layout/MobileNav.tsx
import {useState, useEffect, useCallback, useRef, createContext, useContext, type ReactNode, type ReactElement} from 'react';
import {View, Text} from '@tarojs/components';
import {useTranslations, useLocale} from '@/lib/next-intl-compat';
import {XIcon} from '@/plugins/xicon';
import {useI18nRouter} from '@/i18n/helpers/useI18nRouter';
import {useI18n} from '@/i18n';
import {usePreferences} from '@/core/preferences';
import {fetchListNavigations} from '@/api/hooks/navigation';
import type {siteservicev1_Navigation, siteservicev1_NavigationItem} from '@/api/generated/app/service/v1';

/** 全局抽屉状态上下文 */
const DrawerCtx = createContext<{
    open: boolean;
    setOpen: (v: boolean) => void;
}>({open: false, setOpen: () => {}});

/** 供 Layout 使用的 Provider + 抽屉渲染 */
export function MobileNavProvider({children}: {children: ReactNode}): ReactElement {
    const [open, setOpen] = useState(false);
    return (
        <DrawerCtx.Provider value={{open, setOpen}}>
            {children}
            {open && <MobileNavDrawer />}
        </DrawerCtx.Provider>
    );
}

/** Header 中的汉堡触发按钮 */
export function MobileNavTrigger() {
    const {open, setOpen} = useContext(DrawerCtx);
    return (
        <View
          className='flex items-center justify-center w-[64rpx] h-[64rpx] rounded'
          onClick={() => setOpen(!open)}
          hoverClass='tap-active'
        >
            <XIcon name={open ? 'carbon:close' : 'carbon:menu'} size={20} className='text-textSec' />
        </View>
    );
}

/** 抽屉面板（在 Layout 顶层渲染，不受 Header fixed 嵌套影响） */
function MobileNavDrawer() {
    const {setOpen} = useContext(DrawerCtx);
    const t = useTranslations('navbar');
    const menuT = useTranslations('menu');

    const router = useI18nRouter();
    const locale = useLocale();
    const {theme: themePref, setThemeMode} = usePreferences();
    const {changeLocale} = useI18n();
    const currentMode = themePref.mode;

    const [navigationItems, setNavigationItems] = useState<siteservicev1_NavigationItem[]>([]);
    const [expandedId, setExpandedId] = useState<number | null>(null);

    const close = () => setOpen(false);

    const loadNavigations = useCallback(async () => {
        try {
            const res = await fetchListNavigations({paging: {page: 1, pageSize: 10}}) as unknown as { items: siteservicev1_Navigation[]; total: number };
            if (res.items?.length) {
                const headerNav = res.items.find(nav => nav.location === 'HEADER' && nav.isActive === true);
                if (headerNav?.items?.length) setNavigationItems(headerNav.items);
            }
        } catch (error) {
            console.error('[MobileNav] 加载导航失败:', error);
        }
    }, []);

    // 首次加载
    useEffect(() => {
        loadNavigations();
    }, [loadNavigations]);

    // locale 变化时重新加载导航（用 ref 跳过首次）
    const prevLocaleRef = useRef(locale);
    useEffect(() => {
        if (prevLocaleRef.current !== locale) {
            prevLocaleRef.current = locale;
            loadNavigations();
        }
    }, [locale, loadNavigations]);

    const handleNavigate = (item: siteservicev1_NavigationItem) => {
        close();
        if (!item.url) return;
        // 首页特殊处理：Taro.navigateTo 不触发页面重渲染，用浏览器原生导航
        if (item.url === '/' && typeof window !== 'undefined') {
            window.location.href = window.location.origin + '/';
        } else {
            router.push(item.url);
        }
    };

    const handleAction = (action: () => void) => {
        action();
        close();
    };

    return (
        <View
          className='fixed top-0 left-0 right-0 bottom-0 z-[2000]'
          style={{width: '100vw', height: '100vh'}}
        >
            {/* 半透明遮罩 */}
            <View
              className='fixed top-0 left-0 right-0 bottom-0'
              style={{backgroundColor: 'rgba(0,0,0,0.5)', zIndex: 1}}
              onClick={close}
            />

            {/* 右侧抽屉面板 */}
            <View
              className='fixed top-0 bottom-0 bg-cardBg text-textMain border-s-[1rpx] border-splitLine flex flex-col'
              style={{insetInlineEnd: 0, width: '560rpx', zIndex: 2}}
            >
                {/* 顶部关闭按钮区 */}
                <View
                  className='flex items-center justify-end border-b-[1rpx] border-splitLine'
                  style={{height: '128rpx', padding: '16rpx 32rpx 16rpx 32rpx'}}
                >
                    <View
                      className='flex items-center justify-center rounded-full bg-pageBg'
                      style={{width: '88rpx', height: '88rpx'}}
                      onClick={close}
                      hoverClass='tap-active'
                    >
                        <XIcon name='carbon:close' size={22} className='text-textMain' />
                    </View>
                </View>

                {/* 可滚动内容区 */}
                <View className='flex-1 overflow-y-auto'>
                    {/* 主导航 */}
                    {navigationItems.length > 0 && (
                        <View className='py-[8rpx]'>
                            {navigationItems.map((item) => {
                                const itemId = item.id ?? 0;
                                const hasChildren = (item.children?.length ?? 0) > 0;
                                const isExpanded = expandedId === itemId;

                                return (
                                    <View key={itemId}>
                                        <View
                                          className='flex items-center justify-between px-[32rpx]'
                                          style={{height: '96rpx'}}
                                          onClick={() => {
                                                if (hasChildren) {
                                                    setExpandedId(isExpanded ? null : itemId);
                                                } else {
                                                    handleNavigate(item);
                                                }
                                            }}
                                          hoverClass='tap-active'
                                        >
                                            <View className='flex items-center'>
                                                {item.icon && (
                                                    <View style={{marginInlineEnd: '16rpx'}}>
                                                        <XIcon name={`carbon:${item.icon}`} size={18} className='text-primary' />
                                                    </View>
                                                )}
                                                <Text className='text-body text-textMain'>{item.title}</Text>
                                            </View>
                                            {hasChildren && (
                                                <XIcon
                                                  name='carbon:chevron-down'
                                                  size={16}
                                                  className='text-textThird'
                                                  style={{transform: isExpanded ? 'rotate(180deg)' : 'rotate(0deg)', transition: 'transform 0.2s'}}
                                                />
                                            )}
                                        </View>

                                        {/* 子导航 */}
                                        {hasChildren && isExpanded && (
                                            <View
                                              className='border-s-[2rpx] border-splitLine'
                                              style={{marginInlineStart: '32rpx'}}
                                            >
                                                {item.children!.map((child: siteservicev1_NavigationItem) => (
                                                    <View
                                                      key={child.id?.toString()}
                                                      className='flex items-center px-[24rpx]'
                                                      style={{height: '84rpx'}}
                                                      onClick={() => handleNavigate(child)}
                                                      hoverClass='tap-active'
                                                    >
                                                        {child.icon && (
                                                            <View style={{marginInlineEnd: '16rpx'}}>
                                                                <XIcon name={`carbon:${child.icon}`} size={16} className='text-textThird' />
                                                            </View>
                                                        )}
                                                        <Text className='text-desc text-textSec'>{child.title}</Text>
                                                    </View>
                                                ))}
                                            </View>
                                        )}
                                    </View>
                                );
                            })}
                        </View>
                    )}

                    {/* 分隔线 */}
                    <View className='bg-splitLine' style={{height: '1rpx', margin: '0 32rpx'}} />

                    {/* 用户操作 */}
                    <View className='py-[8rpx]'>
                        <DrawerItem icon='carbon:user' label={menuT('homepage')} onClick={() => handleAction(() => router.push('/user'))} />
                        <DrawerItem icon='carbon:settings' label={menuT('my_profile')} onClick={() => handleAction(() => router.push('/settings'))} />
                    </View>

                    {/* 分隔线 */}
                    <View className='bg-splitLine' style={{height: '1rpx', margin: '0 32rpx'}} />

                    {/* 语言切换 */}
                    <View className='py-[8rpx]'>
                        <View className='flex items-center px-[32rpx]' style={{height: '56rpx'}}>
                            <XIcon name='carbon:earth' size={12} className='text-textThird' />
                            <Text className='text-xs text-textThird' style={{marginInlineStart: '6rpx'}}>{t('language.title')}</Text>
                        </View>
                        <DrawerItem label={t('language.zh-CN')} onClick={() => handleAction(() => changeLocale('zh-CN'))} active={locale === 'zh-CN'} />
                        <DrawerItem label={t('language.en-US')} onClick={() => handleAction(() => changeLocale('en-US'))} active={locale === 'en-US'} />
                    </View>

                    {/* 分隔线 */}
                    <View className='bg-splitLine' style={{height: '1rpx', margin: '0 32rpx'}} />

                    {/* 主题切换 */}
                    <View className='py-[8rpx]'>
                        <View className='flex items-center px-[32rpx]' style={{height: '56rpx'}}>
                            <XIcon
                              name={currentMode === 'dark' ? 'carbon:moon' : currentMode === 'light' ? 'carbon:sun' : 'carbon:monitor'}
                              size={12}
                              className='text-textThird'
                            />
                            <Text className='text-xs text-textThird' style={{marginInlineStart: '6rpx'}}>{t('theme.title')}</Text>
                        </View>
                        <DrawerItem icon='carbon:sun' label={t('theme.light')} onClick={() => handleAction(() => setThemeMode('light'))} active={currentMode === 'light'} />
                        <DrawerItem icon='carbon:moon' label={t('theme.dark')} onClick={() => handleAction(() => setThemeMode('dark'))} active={currentMode === 'dark'} />
                        <DrawerItem icon='carbon:monitor' label={t('theme.system')} onClick={() => handleAction(() => setThemeMode('auto'))} active={currentMode === 'auto'} />
                    </View>
                </View>
            </View>
        </View>
    );
}

/** 抽屉内菜单项 - 增强选中状态视觉反馈 */
function DrawerItem({icon, label, onClick, active, destructive}: {
    icon?: string;
    label: React.ReactNode;
    onClick: () => void;
    active?: boolean;
    destructive?: boolean;
}) {
    // 选中状态：半透明主色背景 + 主色文字 + 加粗
    const bgStyle = active ? {backgroundColor: 'rgba(0,107,230,0.08)'} : {};

    return (
        <View
          className='flex items-center px-[32rpx]'
          style={{height: '88rpx', ...bgStyle}}
          onClick={onClick}
          hoverClass='tap-active'
        >
            {icon && (
                <View style={{marginInlineEnd: '16rpx'}}>
                    <XIcon
                      name={icon}
                      size={18}
                      className={destructive ? 'text-danger' : active ? 'text-primary' : 'text-textSec'}
                    />
                </View>
            )}
            <Text
              className={`text-body flex-1 ${destructive ? 'text-danger' : active ? 'text-primary font-bold' : 'text-textMain'}`}
            >
                {label}
            </Text>
            {/* 选中状态：右侧显示勾选图标 */}
            {active && !destructive && (
                <XIcon name='carbon:checkmark' size={18} className='text-primary' />
            )}
        </View>
    );
}

/** 默认导出保持向后兼容 */
export default MobileNavTrigger;
