// frontend/app/vue/app/components/layout/SearchBar.vue
<script setup lang="ts">
const { t } = useI18n()
const localePath = useLocalePath()
const searchQuery = ref('')

const handleSearch = () => {
  const q = searchQuery.value.trim()
  if (!q) return
  navigateTo(localePath(`/search?q=${encodeURIComponent(q)}`))
}
</script>

<template>
  <div class="mx-2 hidden h-11 max-w-80 flex-1 items-center md:flex lg:max-w-80">
    <div class="relative w-full">
      <XIcon icon="lucide:search" width="16" height="16" class="absolute start-2 top-1/2 -translate-y-1/2 text-muted-foreground" />
      <UiInput
        class="h-full w-full ps-8"
        v-model="searchQuery"
        @keyup.enter="handleSearch"
        :placeholder="t('navbar.top.search_placeholder')"
      />
    </div>
  </div>
</template>

// frontend/app/react/src/components/layout/SearchBar.tsx
'use client';

import React, {useState} from 'react';
import {Input} from '@/components/ui/input';
import {Search} from 'lucide-react';
import {useTranslations} from 'next-intl';
import {useI18nRouter} from '@/i18n/helpers/useI18nRouter';

export default function SearchBar() {
    const t = useTranslations('navbar.top');
    const router = useI18nRouter();
    const [searchQuery, setSearchQuery] = useState('');

    const handleSearch = () => {
        const q = searchQuery.trim();
        if (!q) return;
        router.push(`/search?q=${encodeURIComponent(q)}`);
    };

    return (
        <div className="mx-2 hidden h-11 max-w-80 flex-1 items-center md:flex lg:max-w-80">
            <div className="relative w-full">
                <Search className="absolute start-2 top-1/2 h-4 w-4 -translate-y-1/2 text-muted-foreground"/>
                <Input
                    className="h-full w-full ps-8"
                    value={searchQuery}
                    onChange={(e) => setSearchQuery(e.target.value)}
                    onKeyDown={(e) => {
                        if (e.key === 'Enter') handleSearch();
                    }}
                    placeholder={t('search_placeholder')}
                />
            </div>
        </div>
    );
}
